name: Go

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Cache go module
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        # 获取当前仓库的名称
        REPO_NAME=$(basename $(pwd))
        go build -v -o $REPO_NAME

    - name: Create release artifact
      run: |
        # 获取当前仓库的名称
        REPO_NAME=$(basename $(pwd))
        # 创建一个临时目录用于存放发布文件
        mkdir -p release
        # 将编译后的二进制文件复制到临时目录
        cp $REPO_NAME release/
        # 将 conf 文件夹和 asset 文件夹复制到临时目录
        cp -r conf asset release/
        # 打包临时目录为 tar.gz 文件
        tar -czvf $REPO_NAME.tar.gz -C release .

    - name: Release
      uses: softprops/action-gh-release@v2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          *.tar.gz
      
    - uses: actions/upload-artifact@v4.6.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        path: |
          *.tar.gz