name: Go

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '^1.24'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4.2.2

    - name: Cache go module
      uses: actions/cache@v4.2.3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      if: startsWith(github.ref, 'refs/tags/')
      env:
          NAME: nali
          BINDIR: bin
      run: make releases

    - name: Upload Release
      uses: softprops/action-gh-release@v2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: bin/*
        draft: true
        prerelease: true
      
    - uses: actions/upload-artifact@v4.6.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: build
        path: bin